---
title: "J381M Fall 2022 tidytuesday Week 2"
author: "Hakeoung Hannah Lee"
date: "2022-09-05"
output: html_document
---

```{r}
library(tidytuesdayR)
library(tidyverse)
library(ggtext)

tuesdata <- tt_load("2022-08-30")
pell <- tuesdata$pell
glimpse(pell)
summary(pell)
```


```{r}
UT <- pell %>%
  filter(NAME %in% c("University of Texas at Arlington", "University of Texas at Dallas", "University of Texas at San Antonio", "University of Texas - Austin", "University of Texas - El Paso", "University of Texas Health Science Center at Houston"))
```

```{r}
ggplot() + 
  geom_point(data=UT, aes(x=YEAR, y=AWARD, color=NAME, size=RECIPIENT)) +
  scale_y_continuous(labels = scales::dollar) +
  ggtitle("University of Texas System Pell Grants", subtitle = "Plot shows the total amount of Pell Grants awarded to students at each University of Texas University from 1999 to 2017.") +
  labs(size = "Number of Recipients", caption = "@Hakeoung Hannah Lee | Source: U.S. Department of Education")
```

