---
title: "Week4-TidyTuesday"
author: "Hakeoung Hannah Lee"
date: "2022-09-19"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
tuesdata <- tidytuesdayR::tt_load(2022, week = 37)
bf <- tuesdata$bigfoot
```
```{r}
glimpse(bf)
```

```{r}
#install.packages("lubridate")
#library(lubridate)
library(tidyverse)
```

```{r}
bf_clean <- bf %>%
  filter(!is.na(date)) %>%
  mutate(year = lubridate::year(date)) %>%
  filter(year >= 1990, state == "Texas") %>%
  mutate(season = na_if(season, "Unknown"))
```

```{r}
library(dplyr)
year_freq <- bf_clean %>% count(year)
```

```{r}
library(ggthemes)
library(scales)

plot1 <- ggplot(year_freq, aes(x = year, y = n)) +
  geom_line() +
  geom_point() +
  labs(title = "Number of Bigfoot Sightings Per Year", subtitle = "Texas and Bordering States (since 1990)", x = "Year", y = "count", caption = "@Hakeoung Hannah Lee | Source: 2022-09-13 tidytuesday") +
  theme_economist_white()

plot1
```

```{r adding more information}
bf_states_clean <- bf %>%
  filter(!is.na(date)) %>%
  mutate(year = lubridate::year(date)) %>%
  filter(year >= 1990) %>%
  mutate(season = na_if(season, "Unknown")) %>%
  subset(grepl("Texas|Oklahoma|Arkansas|New Mexico|Louisiana", state))
```

```{r grouping}
bf_states_clean2 <- bf_states_clean %>% add_count(state, year)
```

```{r}
table(bf_states_clean2$n)
```

```{r}
plot2 <- ggplot(bf_states_clean2, aes(x = year, y=n, linetype = state)) +
  geom_point(aes(color=state), size=1) +
  geom_line(aes(color=state)) +
  labs(title = "Number of Bigfoot Sightings Per Year", subtitle = "Texas and Bordering States (since 1990)", x = "Year", y = "count", caption = "@Hakeoung Hannah Lee | Source: 2022-09-13 tidytuesday") +
  theme_few() +
  scale_color_hue()

plot2 + theme(plot.title = element_text(size = 20, face = "bold"), axis.title = element_text(size = 10, face = "bold"), axis.text = element_text(size = 6))
```
```{r}
plot3 <- ggplot(bf_states_clean2, aes(x = year, y=n, color = state)) +
  geom_point(size = 1) +
  geom_line(size = 1) +
  labs(title = "Number of Bigfoot Sightings Per Year", subtitle = "Texas and Bordering States (since 1990)", x = "Year", y = "count", caption = "@Hakeoung Hannah Lee | Source: 2022-09-13 tidytuesday") +
  theme_gray() +
  scale_color_hue()

plot3 + facet_wrap(vars(state)) + theme(plot.title = element_text(size = 20, face = "bold"), axis.title = element_text(size = 10, face = "bold"), axis.text = element_text(size = 6))
```

