---
title: "Week5-TidyTuesday"
author: "Hakeoung Hannah Lee"
date: "2022-09-22"
output: html_document
---

```{r setup}
library(tidyverse)
library(dplyr)
tuesdata <- tidytuesdayR::tt_load(2022, week = 38)
hw <- tuesdata$HydroWASTE_v10
```

```{r}
glimpse(hw)
```

```{r}
#install.packages("janitor")
library(janitor)

hw <- clean_names(hw)
glimpse(hw)
```

```{r}
hw2 <- hw %>%
mutate(qual_loc = as.factor(qual_loc),
      qual_pop = as.factor(qual_pop),
      qual_waste = as.factor(qual_waste),
      qual_level = as.factor(qual_level),
      coast_10km = as.factor(coast_10km),
      coast_50km = as.factor(coast_50km),
      qual_cap = as.factor(qual_cap))
```

```{r}
#install.packages("maps")
library(maps)

world <- map_data("world")
```

```{r}
#install.packages("MetBrewer")
library(MetBrewer)
```


```{r}
hw3 <- hw2 %>%
rename(region = country)%>%
group_by(region)%>%
summarise(total = sum(waste_dis))%>%
mutate(per = (total/sum(total)))

hw3 <- hw3 %>%
  ## Recode certain entries
  mutate(region = recode(str_trim(region), "United States" = "USA",
                            "United Kingdom (Montserrat)" = "UK"))
                            
final = inner_join(world, hw3, by = "region")
```


```{r}
plot <- ggplot(data = final, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) +
  geom_polygon(aes(fill = per)) +
  scale_fill_gradientn(colors = met.brewer("Benedictus"), labels = scales::percent) + 
  theme(axis.text.x = element_blank())+
  theme(axis.text.y = element_blank())+
  theme(axis.title.x = element_blank())+
  theme(axis.title.y = element_blank())+
  labs(title = "Worldwide Map Displaying the Percentage of Treated Wastewater", subtitle = "Discharged by Wastewater Treatment Plants in Each Country", caption = "@Hakeoung Hannah Lee | Source: 2022-09-20 tidytuesday, Github @deepdk/TidyTuesday") +
  theme_gray()
  
plot
```